### ISSUE TITLE
CSI PV Resizing support

### ISSUE THREAD

**Issue by somejfn** [Datera/datera-csi#1]
Hi @mattsmithdatera,

With K8s 1.16 almost out,  and the CSI PV resizing moving to beta state and enabled by default in the feature gates,  what is the timeline for the Datera driver to support it ?

best,

Jfn

**Comment by virgilm** [comment]
The driver has resizing support already, but it is currently in the process of testing/qualification. We'll update when it is officially supported.

**Comment by somejfn** [comment]
Will test 1.0.8 now that it is out. thank you !
