### ISSUE TITLE
Are datera-csi and its components SOX compliant?

### ISSUE THREAD

**Issue by ajays20078** [Datera/datera-csi#6]
Are datera-csi and its components SOX compliant?  To be more specific about the question, we want to know if any of these components can directly or indirectly manipulate actual volume data or not? The concern here is whether it "has access to the data or not", it's not about it "does that or not".

**Comment by virgilm** [comment]
The CSI driver does not manipulate the data on the volume in any way, it only instructs the Datera appliance to create/delete/change policies/take snapshots, and so on via APIs. The CSI driver does not deal with the actual data on the volume in any way.

I hope this answers the question.
